### PR TITLE
Bug 1717636: Add relatedObjects to cluster operator status

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by ecordell** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/960/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws-olm/2567/artifacts/e2e-aws-olm/must-gather/must-gather.log

I don’t see the PackageManifests being collected, but I see everything else. Any ideas?

**Comment by dinhxuanvu** [comment]
We actually never create cluster operator for package server.

**Pull request merged**
