### PR TITLE
Bug 1815957: increase grpc_health_probe timeout

### PR DESCRIPTION
**Pull request by wangzheng422**
**Description of the change:**
increase grpc_health_probe timeout by adding -rpc-timeout=10s

**Motivation for the change:**
the community operator catalog source pod will continue to restart because the healthcheck failed, due to the timeout is too small.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by wangzheng422** [comment]
redhat bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1815957

**Comment by njhale** [comment]
Hi @wangzheng422,

Thanks for submitting your PR! Before we can accept your contribution, we need to determine if the fix should be in newer release streams of OLM, and if it should, backport from those newer versions to 4.3.z. In practice, this means you should open a PR against master with your fix, then cherry-pick the fix to the release-4.4 branch, and then to the release-4.3 branch.

If you change the target branch on your PR to master we can get the ball rolling on a review!

**Comment by wangzheng422** [comment]
link to: https://github.com/operator-framework/operator-lifecycle-manager/pull/1407

**Pull request closed without merging**
