### PR TITLE
[release-4.3] Bug 1807631: Duplicate packages in packageserver APIService response

### PR DESCRIPTION
**Pull request by exdx**
**Description of the change:**
4.3 backport of bugfix - see BZ for details. 

**Motivation for the change:**
Continuation of #1330 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
@exdx Looks like there was some bad merging in the e2e tests. Can you fix?

**Comment by exdx** [comment]
I am a little concerned the console test failing might not be a flake but lets see if it passes.

**Comment by exdx** [comment]
@spadgett could you take a look at this CI result and confirm that there is an issue with this patch going into 4.3 on the console side? I haven't seen this test pass so it doesn't seem like a flake. Thanks!

**Comment by spadgett** [comment]
@exdx This doesn't look like it's just a flake. We expect to get the Jaeger Tracing operator form in the UI test:

https://github.com/openshift/console/blob/release-4.3/frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/global-installmode.scenario.ts#L99

But we're seeing a form for the PlanetScale operator:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/1363/pull-ci-operator-framework-operator-lifecycle-manager-release-4.3-e2e-aws-console-olm/94/artifacts/e2e-aws-console-olm/gui_test_screenshots/855255f4ed0cc57854a627f6f405b101.png

**Comment by exdx** [comment]
Interesting, thanks for the quick feedback. I guess I will look into this more. This did make it into 4.5 and 4.4 with no UI issues though so curious what could be the difference here. 

In order to backport this fix to 4.3 I had to cherry-pick code that enabled the packagserver to List by a label selector. Is this UI code depending on that functionality? It's not apparent from the test, but if console is trying to select based on name=jaeger and that label is not being propagated down to the packageserver its possible its getting the wrong response?

**Comment by spadgett** [comment]
It looks like we use `fieldSelector` and `labelSelector`. The request looks like

> /apis/packages.operators.coreos.com/v1/namespaces/openshift-marketplace/packagemanifests?limit=250&labelSelector=catalog%3Dcommunity-operators&fieldSelector=metadata.name%3D3scale-community-operator

https://github.com/openshift/console/blob/release-4.3/frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx#L437-L450

**Comment by exdx** [comment]
Interesting. Looks like the label selector is being used to specify the queried catalog as community operators - its the field selector that is filtering based on `metadata.name` and is returning the planet scale operator instead of jaeger. we haven't edit the field selector capacity at all. 

I think its possible some of the code that was removed was supplying the correct response based on the field selectors https://github.com/operator-framework/operator-lifecycle-manager/pull/1363/files#diff-bf57e0360adde6e4fd72252ca39438c7L119 - I will have to look into it and potentially add some back

**Pull request merged**
