### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by perdasilva**
**Description of the change:**
Adds me to the owners file as an owner and maintainer.

**Motivation for the change:**
This way I can better support the team through review and approvals

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage
- [x] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/doc`
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
DCO check is complaining but I don't know how you sign commits when the commit was created through the UI :shrug: 

/lgtm

**Comment by perdasilva** [comment]
> DCO check is complaining but I don't know how you sign commits when the commit was created through the UI shrug
> 
> /lgtm

I'll check it out locally - forgot about this T_T

**Comment by perdasilva** [comment]
@kevinrizza quick approve? =D

**Comment by timflannagan** [comment]
@perdasilva It looks like you need to rebate to make branch protection happy 😢

**Comment by timflannagan** [comment]
holding so the bot doesn't go crazy.

/hold

**Comment by awgreene** [comment]
Closing this in favor of https://github.com/operator-framework/operator-lifecycle-manager/pull/2551

**Pull request closed without merging**
