### PR TITLE
changelog for v.0.18.0

### PR DESCRIPTION
**Pull request by exdx**
Signed-off-by: Daniel Sover <dsover@redhat.com>

**Description of the change:**
Changelog for #2116 

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by exdx** [comment]
/hold
this doesn't look right...

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
