### PR TITLE
Apply Subscription.Spec.Config.Annotations to Deployments, Pods, ApiServices

### PR DESCRIPTION
**Pull request by cognifloyd**
**Description of the change:**

Use `Subscription.Spec.Config.Annotations` to apply admin-supplied annotations to an Operator's:
- Deployments
- Pods (via Deployment Spec)
- ApiServices

**Motivation for the change:**

I need a way to annotate operator deployments to satisfy an admissions hook in my on-prem vanilla (not OCP) k8s clusters (The admissions hook requires annotations that say which team is responsible for that deployment).

After discussing in [#olm-dev](https://kubernetes.slack.com/archives/C0181L6JYQ2), it looks like Subscription is the best user (cluster admin) facing API to extend for this purpose, as other resources, like CSV, should generally be opaque to the cluster admin.

So, I added Annotations to SubscriptionConfig in: https://github.com/operator-framework/api/pull/312
That was released in v0.22.0.

**Architectural changes:**

N/A

**Testing remarks:**

No testing yet. I need feedback on this before I do anything else.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Review by stevekuznetsov — COMMENTED** [review]
These changes look good, perhaps @joelanford can do a review here for direction.

**Comment by cognifloyd** [comment]
I just force pushed to signoff my commit and satisfy the DCO check.

**Comment by cognifloyd** [comment]
> Do you own the definition of your validating admission webhook? It strikes me as easier to ensure that Subscriptions have the ownership annotations you need and exclude Deployments that have OLM management labels.

Yes and no. Yes, my team manages the admissions webhook, but the policy on inspecting Deployments was defined by an audit team and whatever tooling they're using (I'm not sure what they're using). So, just modifying that admissions webhook won't satisfy the auditor's policy which ties my hands.

**Pull request merged**
