### PR TITLE
Bug 1797700: [release-4.1] fix(packageserver): cache packagemanifests

### PR DESCRIPTION
**Pull request by njhale**
**Description of the change:**

Backport packagemanifest cache to 4.1.

### CODE REVIEW

**Comment by njhale** [comment]
/hold

This won't pass until the license year fix is backported. There's no use in spamming CI.

**Comment by bparees** [comment]
At this point we are only accepting critical bug fixes for 4.1. This does not seem to meet that target, do you want to close it (and the BZ) or make a case for why it is critical?

**Comment by ecordell** [comment]
@bparees This is a performance fix for the packageserver api. If we find that this becomes critical for some reason in the future, we can re-open.

**Comment by sdodson** [comment]
/lgtm cancel
(to get if off patch manager queries)

**Pull request closed without merging**
