### PR TITLE
install.sh should not abort if openshift olm is not installed

### PR DESCRIPTION
**Pull request by jmazzitelli**
Closes https://github.com/operator-framework/operator-lifecycle-manager/issues/2210

### CODE REVIEW

**Comment by jmazzitelli** [comment]
added sign-off in commit

**Comment by jmazzitelli** [comment]
@timflannagan I had to add the sign-off to the commit - you may need to kick this again

**Comment by jmazzitelli** [comment]
Not sure what else is needed - the tide check is pending with "Not mergeable. Needs approved label"

I assume I'll need a project admin to label with `/approved` to keep it going.

cc @timflannagan

**Comment by benluddy** [comment]
Thanks for fixing this!

**Pull request merged**
