### PR TITLE
Adding description to package manifest object

### PR DESCRIPTION
**Pull request by galletti94**
Solves [ALM-819](https://jira.coreos.com/browse/ALM-819)

/cc @alecmerdler

### CODE REVIEW

**Comment by alecmerdler** [comment]
@galletti94 I think you need to run `make codegen` and commit the generated code.

**Comment by njhale** [comment]
> @galletti94 I think you need to run `make codegen` and commit the generated 

Since codegen has issues with go modules, it's recommended to use `make gen-all` which runs codegen in a go 1.10 container.

**Comment by galletti94** [comment]
@njhale turns out I had an easier time with `make codegen` for some reason. 

I'm still trying to get `make gen-all` to work. The generated code should be the same right?

**Comment by njhale** [comment]
The only difference should be the code generated for openapi; which it looks like did change `pkg/package-server/apis/openapi/zz_generated.openapi.go` 🙂

**Comment by galletti94** [comment]
@njhale @alecmerdler what is the command for re-launching the gitlab-ci checks?

**Comment by alecmerdler** [comment]
@galletti94 Normally I just `git push --force` with the same commit. However, please note that we are having CI issues at the moment.

**Pull request merged**
