### PR TITLE
Fix dependency on github.com/openshift/api

### PR DESCRIPTION
**Pull request by grdryn**
It looks like the openshift/api project deleted all of their tags, so
now the following error is thrown any time we run e.g. a `go mod tidy`
in any project that depends on it:

```
go: github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
```

For this change, all I did was remove the entries in "require" and
"replace" in the go.mod, manually added the new "replace" and ran `go
mod tidy`.

See https://github.com/openshift/api/issues/456 for more info on the
issue.

----

#

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
@grdryn Thanks for the PR - could you run `make vendor` as well, to vendor the changes you've made here? Then we can validate them.

**Comment by grdryn** [comment]
@ecordell I've updated that now, thanks!

**Comment by ecordell** [comment]
@grdryn what changed when you force pushed? I don't see a difference

**Comment by grdryn** [comment]
@ecordell it was just a rebase because of some conflicts in the generated files (I think it was `go.sum` and `vendor/modules.txt`?).

I'm not familiar enough with the failing e2e tests to know if they're failing because of my changes, are they?

**Comment by njhale** [comment]
@grdryn if you could rebase when you get the chance, I'll circle back for a swift review to get this in.

**Comment by grdryn** [comment]
@njhale I've rebased & bumped the commit of openshift/api (I don't really know what it should be set to, so I've just used the latest commit on master).

**Comment by grdryn** [comment]
/test unit

^Unit tests seem to work fine for me locally :man_shrugging:

**Comment by ecordell** [comment]
This was resolved in https://github.com/operator-framework/operator-lifecycle-manager/pull/1370

**Pull request closed without merging**
