### PR TITLE
Makefile,test: Remove the test/rh-operators directory

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**
Update the root Makefile and remove the target for running the metric
e2e tests.

Remove the test/rh-operators directory.

**Motivation for the change:**
Lowers maintenance burden by removing tests that add little value and helps decouple upstream OLM from housing OCP-specific content.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Comment by timflannagan** [comment]
Manually merging as the labels as present and these changes don't influence e2e failures.

**Pull request merged**
