### PR TITLE
Validate clusterserviceversion

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

Fixed https://github.com/operator-framework/operator-lifecycle-manager/issues/1155

### CODE REVIEW

**Comment by awgreene** [comment]
Thanks for submitting this PR @clyang82!

#1157 was created to address this issue.

**Comment by clyang82** [comment]
@awgreene That is great. Good to hear that this issue will be addressed. Thanks. I am going to close this PR once your fix was merged.

**Comment by awgreene** [comment]
> @awgreene That is great. Good to hear that this issue will be addressed. Thanks. I am going to close this PR once your fix was merged.

@clyang82 Great, I will work on getting the PR through quickly.

**Comment by clyang82** [comment]
> > @awgreene That is great. Good to hear that this issue will be addressed. Thanks. I am going to close this PR once your fix was merged.
> 
> @clyang82 Great, I will work on getting the PR through quickly.

Thanks @awgreene

**Comment by clyang82** [comment]
#1157 was merged. so close this one...

**Comment by clyang82** [comment]
@awgreene the original issue(#1155) I reported was not fixed, because the `deploy/upstream/quickstart/crds.yaml` was not updated. 

@gallettilance Do we need to update release dir by using `controller-gen`? Thanks.

**Comment by clyang82** [comment]
check the code again. the crds.yaml and olm.yaml will be generated when a new release is made.

**Pull request closed without merging**
