### PR TITLE
Remove cleanup from startup

### PR DESCRIPTION
**Pull request by ecordell**
**Description of the change:**
Remove cleanup from startup

**Motivation for the change:**
a series of cleanup steps run on start, but they are only required
when updating from very old versions of olm. it doesn't make sense to
carry them forever.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by njhale — APPROVED** [review]
This seems fine. The versions of OLM that the cleanup addresses are obsolete.

Users can step through an intermediate version if they want a seamless upgrade anyway.

/lgtm

**Comment by ecordell** [comment]
/hold

want to double check that we don't need https://github.com/operator-framework/operator-lifecycle-manager/commit/05f5417a37c6b567c70bf98fbe5197fa707b958a#diff-4ce7e916862e18b439f8ce8edbf0b0a85f384589f0ef2b8c5ff32237cb907da9

**Comment by ecordell** [comment]
/hold cancel

that one looks fine - hasn't been needed since ocp 4.4

**Comment by timflannagan** [comment]
Need to investigate why that e2e-tests action is continuously timing out so the openshift-bot doesn't perma-retest.

/hold

**Pull request merged**
