### PR TITLE
Fix trailing slash in the github.com/go-bindata/go-bindata/v3/go-bindata module tool

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**
Update the tools.go and remove the trailing slash in the
`github.com/go-bindata/go-bindata/v3/go-bindata` module.

When attempting to run `make vendor` from the root repository, the
following error is produced:

```bash
$ make vendor
go mod tidy
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/ocp/manifests/latest
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/upstream/manifests/latest
github.com/operator-framework/operator-lifecycle-manager imports
	github.com/go-bindata/go-bindata/v3/go-bindata/: malformed import path "github.com/go-bindata/go-bindata/v3/go-bindata/": trailing slash
make: *** [Makefile:176: vendor] Error 1
```

After after removing the trailing slash, updating the vendor tree was
successful:

```diff
$ git diff tools.go
diff --git a/tools.go b/tools.go
index 387556b9..949acdc9 100644
--- a/tools.go
+++ b/tools.go
@@ -3,7 +3,7 @@
 package tools

 import (
-       _ "github.com/go-bindata/go-bindata/v3/go-bindata/"
+       _ "github.com/go-bindata/go-bindata/v3/go-bindata"
        _ "github.com/golang/mock/mockgen"
        _ "github.com/googleapis/gnostic"
        _ "github.com/maxbrunsfeld/counterfeiter/v6"
```
```bash
$ make vendor
go mod tidy
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/ocp/manifests/latest
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/upstream/manifests/latest
go mod vendor
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/ocp/manifests/latest
warning: ignoring symlink /home/tflannag/go/src/github.com/operator-framework/operator-lifecycle-manager/deploy/upstream/manifests/latest
```

**Motivation for the change:**
Unable to successfully update the root modules when running any `go mod *` command.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by ecordell** [comment]
/approve

sometime soon we should bump to 1.16 and remove bindata

**Comment by timflannagan** [comment]
No need to respin extra clusters for this kind of change.

/override ci/prow/e2e-upgrade
/override ci/prow/e2e-aws-olm

**Pull request merged**
