### PR TITLE
[release-4.7] Bug 1989780: installplans: retry crd updates on conflicts

### PR DESCRIPTION
**Pull request by joelanford**
Manual cherry pick of #2293

### CODE REVIEW

**Comment by bandrade** [comment]
/lgtm 
/label qe-approved

kubectl exec catalog-operator-7f656b6d67-mcd82  -n olm -- olm --version                                                                                                                                                             130 ↵
OLM version: 0.17.0
git commit: 5eb1fa6ad6ecfbf1263a145e54e5bd181a078097

1. Install operator into a namespace (e.g 3scale from OperatorHub. This will install CRDs onto the cluster
```
kubectl get csv -n olm           
NAME                  DISPLAY          VERSION   REPLACES              PHASE
etcdoperator.v0.9.4   etcd             0.9.4     etcdoperator.v0.9.2   Succeeded
packageserver         Package Server   0.17.0                          Succeeded
```



2. Run some script that constantly updates the CRDs of the installed operator to mimic some event updating the CRD
```
 while true; do        
    kubectl patch crd etcdclusters.etcd.database.coreos.com  --type=json -p='[{"op" : "add", "path" : "/metadata/labels/test", "value": "test"}]'
    kubectl patch crd etcdclusters.etcd.database.coreos.com --type=json -p='[{"op" : "remove", "path" : "/metadata/labels/test"}]'
done

customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
The request is invalid
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com patched

The requests fail when an Operator is being installed

```
3. Install the same operator into a different namespace 

```
kubectl get csv --all-namespaces 
NAMESPACE   NAME                  DISPLAY          VERSION   REPLACES              PHASE
etcd-1      etcdoperator.v0.9.4   etcd             0.9.4     etcdoperator.v0.9.2   Succeeded
etcd        etcdoperator.v0.9.4   etcd             0.9.4     etcdoperator.v0.9.2   Succeeded
olm         etcdoperator.v0.9.4   etcd             0.9.4     etcdoperator.v0.9.2   Succeeded
olm         packageserver         Package Server   0.17.0                          Succeeded
```

4. Inspect for failed install plan 
```
kubectl get ip --all-namespaces                            
NAMESPACE   NAME            CSV                   APPROVAL    APPROVED
etcd-1      install-shkw9   etcdoperator.v0.9.4   Automatic   true
etcd        install-mbkfl   etcdoperator.v0.9.4   Automatic   true
olm         install-lkfh5   etcdoperator.v0.9.4   Automatic   true
```

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.50

adding cherry-pick approved

**Comment by timflannagan** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/pull/2351

**Pull request merged**
