### PR TITLE
[wip] adding metric cardinality tests

### PR DESCRIPTION
**Pull request by Bowenislandsong**
This commits adds a script to run metric cardinality tests from origin/test/extended/Prometheus test package. The test package will remain effective with operators uninstalled from the cluster because alerts and messages fired to Prometheus on the cluster are not erased.

### CODE REVIEW

**Comment by benluddy** [comment]
Can this live in the job config instead of in the OLM repo?

**Comment by Bowenislandsong** [comment]
> Can this live in the job config instead of in the OLM repo?

thought it's cleaner here .... I know some projects have it in the config but i think its messy

**Comment by benluddy** [comment]
I'll let others share their opinions, but my preference is to put this in `openshift/release` because it is exclusively targeting OpenShift.

**Comment by Bowenislandsong** [comment]
> I'll let others share their opinions, but my preference is to put this in `openshift/release` because it is exclusively targeting OpenShift.

Ahh, if you put it that way, then you are right, it makes more sense. I'll move it after i'm done with PR testing.

**Comment by Bowenislandsong** [comment]
superseded by https://github.com/openshift/release/pull/7731
/close

**Pull request closed without merging**
