### PR TITLE
OCPBUGS-8993: add namespace label to InstallPlanStepAppliedWithWarnings

### PR DESCRIPTION
**Pull request by simonpasquier**
**Description of the change:**

This change updates the expression of InstallPlanStepAppliedWithWarnings to aggregate the result by namespace.

**Motivation for the change:**

The alerting consistency guide [1] requires the following:

`Alerts SHOULD include a namespace label indicating the alert's source.`

[1] https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Comment by perdasilva** [comment]
triggering rebase from this side to get this through

**Comment by perdasilva** [comment]
merging as CI is green and we have both approval and lgtm

**Pull request merged**
