### PR TITLE
Bug 1791851: [release-4.2] Update license year

### PR DESCRIPTION
**Pull request by Bowenislandsong**
Happy New Year! This cherry picked PR was done in 2019. The verify test
requests that our license year be changed to 2020.

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by Bowenislandsong** [comment]
@operator-framework/patch-managers Could I get help to skip bugzilla + cherry-pick labels and merge this license year update PR? Thank you!

**Comment by jwforres** [comment]
I will override the bugzilla/valid-bug given it is just changing license years, but cherry-pick-approved i'd prefer to wait for the merge window to open back up at the end of the week, the next patch manager should see it show up in the query

**Comment by Bowenislandsong** [comment]
> I will override the bugzilla/valid-bug given it is just changing license years, but cherry-pick-approved i'd prefer to wait for the merge window to open back up at the end of the week, the next patch manager should see it show up in the query

Thank you! I will create similar PRs for different branches in a bit.

**Comment by Bowenislandsong** [comment]
> @Bowenislandsong: No Bugzilla bug is referenced in the title of this pull request.
> To reference a bug, add 'Bug XXX:' to the title of this pull request and request another bug refresh with `/bugzilla refresh`.

oops.

**Comment by crawford** [comment]
Copyright years listed in source aren't generally updated after creation; certainly not in a release branch.

**Pull request closed without merging**
