### PR TITLE
Bug 1738203: Add relatedObjects to cluster operator status 

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by eparis** [comment]
/retitle Bug 1745272: Add relatedObjects to cluster operator status

**Comment by eparis** [comment]
There was no 4.2 bugzilla. I created it. We need to wait for QE to verify this is fixed in master. Then run `/bugzilla refresh`

**Comment by ecordell** [comment]
/hold

This will need to be replaced based on newer understanding of `relatedObjects` (see #1018)

**Pull request merged**
