### PR TITLE
Remove extra jobLabel

### PR DESCRIPTION
**Pull request by maticue**
**Description of the change:**

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by awgreene** [comment]
Thanks for the submission @maticue 
/ok-to-test

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by perdasilva** [comment]
@maticue could you please fix the DCO check and rebase?

**Comment by perdasilva** [comment]
@maticue due to the DCO issue, I cannot merge. I've taken the liberty to clone your PR and resubmit it: #2951 
I hope this is ok with you. I'm sorry about the delay, and thank you so much for your contribution!!!

**Pull request closed without merging**
