### PR TITLE
Update to k8s v0.28.5 and other operator-framework components

### PR DESCRIPTION
**Pull request by tmshort**
### Summary

Updates to latest operator-framework/api and operator-framework/operator-registry, which requires updates to k8s v0.28.x (v0.28.5 in this case).
Update code to be compatible with these updated dependencies.
`kind` is kinda stuck at k8s 1.27.3, so I couldn't update the testing for that.

### Update k8s to v0.28.5

This also updates to the latest operator-framework api and operator-registry

`kind` is still at v0.20.0 (k8s 1.27.3) as it's the latest version

### Update code for k8s v0.28.5 compatibility

Fix unit-tests as well

### Update codegen

Hack `scripts/update_codegen.sh` script to continue to generate code using the deprecated scripts. The deprecated scripts now call into each other, and unfortunately, `go mod vendor` doesn't keep permission bits around.
So, we need to update the execute permissions on a vendored script.

The new `kube_codegen.sh` doesn't work when the repository path is outside the package name, see:

https://github.com/kubernetes/code-generator/issues/165

The workaround is to create symlinked directories to fool `kube_codegen.sh` into thinking the path is correct. But first we'd have to start using the new script.

Once `kube_codegen.sh` is fixed, we should migrate to it (which is a non-trivial task).

## Motivation for the change:

operator-framework/api and operator-framework/operator-registry have been updated to k8s v0.28.x

## Reviewer Checklist
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by tmshort** [comment]
I meant to...
/hold

**Review by grokspawn — APPROVED** [review]

**Pull request merged**
