### PR TITLE
chore(api): vendor the new version of api repo

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vudinh@outlook.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Review by gallettilance — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
Recycling this check as some of the consistent e2e failures in the past couple of runs are due to flakes that had landed in master recently.

**Pull request merged**
