### PR TITLE
[release-4.5] Bug 1878297: remove duplicate catalog source pod when polling

### PR DESCRIPTION
**Pull request by exdx**
**Description of the change:**
Fix of #1758 

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by markmc** [comment]
(patch manager) this seems like quite a large and risky change for a relatively low-impact issue. What am I missing?

**Comment by exdx** [comment]
The following 4.5 backports should be brought in if we want to support better catalog polling UX for customers in 4.5.z. Polling will continue to work without these fixes but will not work as effectively. 

* #1760 (merged)
* #1764 (merged) 
* #1780 
* This PR #1765 


Just depends how much we expect customers to use this feature in 4.5, versus in 4.6 where catalog polling is clearly being used as the default red hat operator catalogs will ship with polling enabled.

**Comment by exdx** [comment]
Also worth pointing out that all the fixes work together to provide better UX, we can't really pick and choose which ones we want. In particular #1780 unlocks the rest of the fixes to work as intended.

**Comment by exdx** [comment]
@operator-framework/patch-managers 

Catalog polling is not going to work properly in 4.5.z for Red Hat catalogs as well as for the IBM teams that are publishing catalogs for their customers without this fix going in.

If we don't backport, shorter polling intervals won't work correctly (minimum will always be 15 minutes), there will always be multiple catalog pods running on the cluster per catalog (only one serves traffic), and edge cases where the updated catalog fails to start will not be handled well. So polling will still work in the base case, but the UX will be worse. As customers move more to the new index-based catalog format and adopt polling in their existing clusters this can be an issue. 

cc @kevinrizza

**Comment by exdx** [comment]
Also in terms of risk all the changes in this PR are to one file that deals exclusively with polling logic. Catalog polling is an opt-in feature and these changes do not affect any other behavioral aspects of OLM.

**Pull request merged**
