### PR TITLE
Fix example string for svg icon types

### PR DESCRIPTION
**Pull request by ivandov**
Valid values are listed in the OpenAPISchema specification of the ClusterServiceVersion CRD

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.7.0/03-clusterserviceversion.crd.yaml#L124-L128

**Description of the change:**
Fix documentation example for SVG icon types

**Motivation for the change:**
Using the example `image/svg` without the `+xml` suffix will cause rendering errors in OCP.

**Architectural changes:**
None

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Review by exdx — APPROVED** [review]
/ok-to-test
/lgtm

**Review by timflannagan — APPROVED** [review]

**Comment by perdasilva** [comment]
@ivandov could you please fix the DCO action? **NOTE** I've rebased the PR from this side. So, you should do a `git pull --rebase && git commit --sign --amend && git push`

### DCO
There is one commit incorrectly signed off. This means that the author of this commit failed to include a Signed-off-by line in the commit message.

To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> in every commit message. You can also do this automatically by using the -s flag (i.e., git commit -s).

Here is how to fix the problem so that this code can be merged.

### Rebase the branch
If you have a local git environment and meet the criteria below, one option is to rebase the branch and add your Signed-off-by lines in the new commits. Please note that if others have already begun work based upon the commits in this branch, this solution will rewrite history and may cause serious issues for collaborators ([described in the git documentation](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) under "The Perils of Rebasing").

You should only do this if:

You are the only author of the commits in this branch
You are absolutely certain nobody else is doing any work based upon this branch
There are no empty commits in the branch (for example, a DCO Remediation Commit which was added using --allow-empty)
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin patch-1

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by perdasilva** [comment]
closing in favor of #2953 - due to DCO blocking the merge. @ivandov I hope it's ok with you that I've taken the liberty of cloning your PR.

**Pull request closed without merging**
