### PR TITLE
Catalog source affinity

### LINKED ISSUE #2960: Add affinity customization to catalog source grpc pods
## Feature Request

Opening here because the PR in the api repo doesn't seem to be getting any attention. This is the issue I raised in last weeks (25th May) Operator Framework community meeting.

**Is your feature request related to a problem? Please describe.**
At the moment, grpc catalog sources can be customised with nodeselectors and tolerations. This doesn't cover the case where a manifest list is used to allow the catalog source to run on multiple architectures, because there is no way to specify multiple architectures without specifically changing node labels/taints.

**Describe the solution you'd like**
Add affinity customization so that multiple architectures can be selected with standard labels. Open to other solutions, but this seems like the most simple one to me.

Work so far:
- PR for the API: https://github.com/operator-framework/api/pull/279
- Changes for OLM (won't open a PR for this yet because it has modified vendor code): https://github.com/operator-framework/operator-lifecycle-manager/compare/master...Jamstah:operator-lifecycle-manager:catalog-source-affinity

### PR DESCRIPTION
**Pull request by Jamstah**
**Description of the change:**

Add affinity customization to catalog sources

Closes #2960

**Motivation for the change:**

Enable multi-architecture catalog images to limit scheduling to their supported architectures.

**Architectural changes:**

n/a

**Testing remarks:**

Basically a copy paste of the same thing for tolerations.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by Jamstah** [comment]
Opened as a draft, partly to let the tests run, and partly to ask a question.

The API change hasn't been put into a release yet - is that something I should wait for before finalizing the PR?

**Comment by perdasilva** [comment]
> Opened as a draft, partly to let the tests run, and partly to ask a question.
> 
> The API change hasn't been put into a release yet - is that something I should wait for before finalizing the PR?

Hi @Jamstah - thanks heaps for this ^^
Yeah, I think we should cut a release of the api repo, then update the mod file to point to it before we can merge this PR.
I'll reach out to the team to see if we can get that happening.

**Comment by Jamstah** [comment]
Great. LMK when that's happened and I can rebase and revendor.

**Comment by Jamstah** [comment]
OK, should be all done.

**Pull request merged**
