### PR TITLE
[release-4.6] Bug 1929335: Only re-create operator resource if it has existing components

### PR DESCRIPTION
**Pull request by joelanford**
This is a manual cherry-pick of #1938

/assign njhale

_(This is my best impression of the openshift-cherry-pick robot's PR message :stuck_out_tongue:)_

### CODE REVIEW

**Comment by njhale** [comment]
/retest

I want to see if the failures are subtle flakes or somehow related (they don't look related, but we should still check).

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
Cherry-picked #2016 into this PR to avoid the flaky test making into the 4.6 branch.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
