### PR TITLE
[release-4.7] Bug 1924467: Bumps k8s.io dependencies to v0.20.6

### PR DESCRIPTION
**Pull request by timflannagan**
Manual cherrypick of #2101 as there were merge conflicts.

Tacked on a couple of no-op changes:

- Removed the trailing slash in the tools.go that was causing `go mod *` commands to fail.
- Updated the OWNERS file to add myself as a reviewer and pruned GH aliases that no longer work at RH or aren't involved in the upstream project anymore.
- Added the `go mod verify` command to the `make vendor` target to verify the dependencies after updating them.

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
Hmm looks like prow is stuck?

**Pull request merged**
