### PR TITLE
Remove kubeconfig flag

### PR DESCRIPTION
**Pull request by perdasilva**
**Description of the change:**
While developing the system/cluster runtime constraints story, I discovered that if `controller-runtime` is in the import path, the go flag library panics due to the `kubeconfig` flag getting redefined. The `controller-runtime` library defines it [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/config/config.go#L39)

This PR refactors the `catalog` cmd to remove the kubeconfig flag

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
Looking good.
/lgtm

**Review by joelanford — APPROVED** [review]
/approve

**Review by anik120 — APPROVED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
Need to figure out how to get passed e2e in order to merge this PR. In the meantime, I'm putting a hold on it to avoid spamming test runs and notifications.
/hold

**Comment by perdasilva** [comment]
obsolete given #2362

**Pull request closed without merging**
