### PR TITLE
Fixes godoc rendering

### PR DESCRIPTION
**Pull request by m1kola**
Follow up for https://github.com/operator-framework/operator-lifecycle-manager/pull/2933/files#r1132142964

Before:
Screenshot 2023-03-14 at 14 31 45

After:
Screenshot 2023-03-14 at 14 31 35

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by tmshort** [comment]
It's a comment. As long as `go fmt ./...` doesn't try to undo it...
/lgtm
/approve

**Review by tmshort — APPROVED** [review]

**Review by perdasilva — APPROVED** [review]
lgtm

**Review by anik120 — COMMENTED** [review]
@m1kola looks like this needs a rebase.

**Comment by m1kola** [comment]
Rebased. Please take another look

**Comment by m1kola** [comment]
@perdasilva I had to rebase becaues github check was complaining that the branch is out of date. Could you please lgtm again? Nothing changed apart from rebase.

**Pull request merged**
