### PR TITLE
README: fix broken links

### PR DESCRIPTION
**Pull request by dtrifiro**
**Description of the change:**

Fix broken links in README

**Motivation for the change:**

Links are broken

**Architectural changes:**

None

**Testing remarks:**

None

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by tmshort** [comment]
Needs another rebase

**Comment by dtrifiro** [comment]
Rebased

**Pull request merged**
