### PR TITLE
chore(manifests): recut 0.8.1

### PR DESCRIPTION
**Pull request by njhale**
Cut 0.8.1 pointing at new upstream image `quay.io/operator-framework/olm`

### CODE REVIEW

**Comment by njhale** [comment]
/hold

Looks like operatorhub.io is pointing to a different quickstart directory. Will fix.

**Comment by njhale** [comment]
/hold cancel

Updated the pathing for `olm.yaml` to match operatorhub.io's instructions.

**Comment by ecordell** [comment]
/lgtm 

🎉

**Comment by ecordell** [comment]
@njhale sorry for the hold - just noticed that community operators got created in `/manifests` which would not be good

**Comment by njhale** [comment]
> @njhale sorry for the hold - just noticed that community operators got created in `/manifests` which would not be good

Ahh - nice catch. I'll make sure it's removed.

**Pull request merged**
