### PR TITLE
fix(build): Fix install_local.sh calls

### PR DESCRIPTION
**Pull request by aravindhp**
Update the template directory of the install_local.sh calls in the run-local and run-local-shift targets.

### CODE REVIEW

**Comment by rodrigovalin** [comment]
Waiting for this to be merged, in the meantime, applying changes locally

**Comment by ecordell** [comment]
I'm pretty sure that this is actually an issue with this line: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/scripts/package-release.sh#L28 not being cross-platform.

These scripts work with macOS's version of `cp`, I think we should just find a cross-platform way to do that instead.

**Comment by njhale** [comment]
Maybe [this](https://twilblog.github.io/macos/linux/cp/copy/2017/02/03/macos-unix-cp-madness.html) will help.
```
cp -R ${charttmpdir}/olm/templates/. ${chartdir}
```

**Comment by aravindhp** [comment]
Ah yes! That works for me. Should I close this PR and let you apply that fix?

**Comment by ecordell** [comment]
@aravindhp I just did tacked it onto another branch I will push up shortly, don't worry about it.

Thanks!

**Pull request closed without merging**
