### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#510 and doesn't change existing behavior

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
this looks good, but the manifests are generated from `/deploy`, so the manifests will need to change there in order to merge.

**Comment by guillaumerose** [comment]
Thanks for the advice @ecordell !

I hope what I did is not too far from what you think. I tried to keep the annotation as close as possible from ocp and not leak it in upstream. 

This script adds the annotations at the end of the generation. The main issue we that is we need to deserialize/serialize the YAML. It changes the indentation, etc. With yq v3, comments are preserved but indents changed in some places.

Let me know what you think!

**Comment by guillaumerose** [comment]
Almost all green. How can I relaunch the failed github action?

**Pull request merged**
