### PR TITLE
fix(catalog): Fix subscriptions without a sourceNamespace hang forever

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@ecordell Ready for review. PTAL

**Comment by ecordell** [comment]
@dinhxuanvu this looks great, but I think we need at least a unit test for this :)

also it looks like it needs a rebase

**Comment by ecordell** [comment]
/hold

holding until master is open for 4.2 😢

**Pull request merged**
