### PR TITLE
Revert "chore: update o-f/api dependency to v0.17 (#2848)"

### PR DESCRIPTION
**Pull request by anik120**
This reverts commit bd97e32644f5a6c5a2b87668df5261a4da62a2a6.

An older v0.17.0 release of operator-framework/api had the spec.RunAsRoot
field, which has [now been updated to be the spec.GrpcPodConfig.SecurityContextConfig
field](https://github.com/operator-framework/api/pull/261). Reverting #2848 so that
the new	v0.17.0	can be pulled in. See [this comment](https://github.com/operator-framework/operator-lifecycle-manager/pull/2848#issuecomment-1233172716) for more info.	

Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>

**Description of the change:**

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Review by timflannagan — APPROVED** [review]

**Comment by anik120** [comment]
@dinhxuanvu done.

**Comment by dinhxuanvu** [comment]
Has this change made it to downstream?

**Comment by anik120** [comment]
No it did not

**Review by dinhxuanvu — APPROVED** [review]
/approve

**Comment by tylerslaton** [comment]
🤞🏻 

/lgtm

**Pull request merged**
