### PR TITLE
Bump OLM version to 0.15.0

### PR DESCRIPTION
**Pull request by anik120**
**Description of the change:**

This PR bumps the version of OLM to 0.15.0

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
/approve

this should have no effect on the tests, but I kicked them anyway.

**Comment by anik120** [comment]
Merging this manually since master is closed currently.

**Pull request merged**
