### PR TITLE
Rename CI github workflows

### PR DESCRIPTION
**Pull request by timflannagan**
Signed-off-by: timflannagan <timflannagan@gmail.com>

**Description of the change:**
Update the various CI workflows names that are run on a per-PR basis to
help distinguish between individual action runs when interacting with
the github UI.

**Motivation for the change:**

Interacting with the 'actions' tab in the Github UI can be challenging when trying to view individual action runs. This is because all of the CI-related workflows are currently named 'ci', which makes filtering out for specific workflows more challenging, requiring you to hover over each action to determine the resolved link. The following screenshot shows the current interaction:

Screenshot from 2021-11-12 12-37-59

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage
- [x] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/doc`
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Review by timflannagan — COMMENTED** [review]
Just a quick note: I elected to not update the e2e-tests workflow as the 'ci' workflow name still seemed appropriate. I don't have a strong opinion in either case, so I'm happy to update and change that as well.

**Review by njhale — APPROVED** [review]
/approve

**Comment by timflannagan** [comment]
Manually overriding the failed e2e test as this PR only affects the naming of the workflow(s) and nothing user-facing.

**Pull request merged**
