### PR TITLE
Tolerations & Resources Override using .Subscription.Config

### PR DESCRIPTION
**Pull request by umangachapagain**
**Description of the change:**
(feat) inject 'Tolerations' & 'Resources' from config

Updated deployment initializer function to inject tolerations
and resources specified in pod configuration of subscription
into deployment object.

- Toleration will be appended if it does not exist
- Resources will be overwritten

(test) update e2e test

**Motivation for the change:**
#1298 

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage 
- [x] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/docs` 
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by hochdorf** [comment]
@umangachapagain was this feature intentionally planned to delete the resources section from the operator deployment even though the related config section is not defined in the subscription?

Based on the code changes and based on my tests if the resources config is not defined in the subscription but it was given in the CSV for the operator then it will be removed from the deployment during installation.

We define the resource needs of an operator on the CSV level because in this way you can define it differently for the separate versions.
After this feature, it's not possible.

Is this behaviour conceptual? Or just a bug?

**Comment by umangachapagain** [comment]
> @umangachapagain was this feature intentionally planned to delete the resources section from the operator deployment even though the related config section is not defined in the subscription?
> 
> Based on the code changes and based on my tests if the resources config is not defined in the subscription but it was given in the CSV for the operator then it will be removed from the deployment during installation.
> 
> We define the resource needs of an operator on the CSV level because in this way you can define it differently for the separate versions.
> After this feature, it's not possible.
> 
> Is this behaviour conceptual? Or just a bug?
>
It's a bug. The intention was to override resources spec, but not blindly.

Please report a bug with your findings.

**Comment by hochdorf** [comment]
> umangachapagain

Thanks! 
https://github.com/operator-framework/operator-lifecycle-manager/issues/1912

**Pull request merged**
