### PR TITLE
Revert "Bug 1905299: fix(olm): Verify ServiceAccount ownership before installing deployment"

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Reverts operator-framework/operator-lifecycle-manager#1904

Reason: The fix in this PR is a dup from another merged PR: #1881

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
/hold
Will wait until master is open again.

**Comment by njhale** [comment]
/approve
/retest

I wonder if there's some procedure we can adopt when writing or submitting bug fixes that will help us catch duplicates like this? e.g. split the patch into two commits: failing test in the first, fix in the second.

**Comment by dinhxuanvu** [comment]
> /approve
> /retest
> 
> I wonder if there's some procedure we can adopt when writing or submitting bug fixes that will help us catch duplicates like this? e.g. split the patch into two commits: failing test in the first, fix in the second.

The two PRs were merged a few days apart so I believe at the time I was working on this, my local master might have not had the other fix. The test case I added was a negative test case meaning it was supposed to fail.

**Comment by dinhxuanvu** [comment]
No longer needed and replaced by #2029 
/close

**Pull request closed without merging**
