### PR TITLE
[release-4.1] Bug 1775322: Enable multiple namespaces sync if catsrc is updated in global ns

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Cherry-pick #1125

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@operator-framework/patch-managers PTAL

**Comment by njhale** [comment]
/hold

verify is failing and the retest bot is churning on a non-flake.

**Comment by dinhxuanvu** [comment]
This PR is closed as it is not a critical bug and 4.1 is EOL.

**Pull request closed without merging**
