### PR TITLE
[release-4.7] Bug 1937375: only override deployment resources when explicitly defined in subscription config

### PR DESCRIPTION
**Pull request by joelanford**
This is a manual cherry-pick of #2010

### CODE REVIEW

**Comment by joelanford** [comment]
Seems to be failing because the `operator-framework/api` commit that this PR requires pulls in controller-runtime v0.8.0, which requires go1.15+.

**Comment by timflannagan** [comment]
@joelanford Looks like something was pushed recently to the release-4.7 branch and now requires a rebase.

**Pull request merged**
