### PR TITLE
Allow ConsoleYAMLSample resources from bundle manifests

### LINKED ISSUE #1615: Support ConsoleYamlSample in bundle manifests
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to add `ConsoleYamlSample`s to my operator, but at the moment, I have to run an init hook in my operator pod to install them into the cluster

**Describe the solution you'd like**
Be able to drop `ConsoleYamlSample`s into the bundle `manifests` directory and have them applied to the cluster.

I did try this, and get `UnsupportedResource` on the InstallPlan
```yaml
    - resolving: ibm-integration-platform-navigator.v4.0.1
      resource:
        group: console.openshift.io
        kind: ConsoleYAMLSample
        manifest: >
          {"apiVersion":"console.openshift.io/v1","kind":"ConsoleYAMLSample","metadata":{"name":"pn-sample-1"},"spec":{"description":"PN
          Sample","snippet":false,"targetResource":{"apiVersion":"integration.ibm.com/v1beta1","kind":"PlatformNavigator"},"title":"Sample
          1","yaml":"---\napiVersion: integration.ibm.com/v1beta1\nkind:
          PlatformNavigator\nmetadata:\n    name: cp4i-navigator\n    namespace:
          cp4i\nspec:\n    license:\n        accept: true\n    mqDashboard:
          true\n    replicas: 3\n    version: 2020.2.1\n"}}
        name: pn-sample-1
        sourceName: pn
        sourceNamespace: openshift-marketplace
        version: v1
      status: UnsupportedResource
```

### PR DESCRIPTION
**Pull request by Jamstah**
**Description of the change:**
Allow the inclusion of samples in the bundle manifest

Closes #1615

**Motivation for the change:**
Ease of deployment of samples for the console

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by Jamstah** [comment]
I feel like I should be updating `test/e2e/bundle_e2e_test.go` to add the new type to the tests, but I can't work out what makes the test bundle so I could add a `ConsoleYamlSample` to it. Any pointers?

**Comment by njhale** [comment]
Sorry for the delayed response @Jamstah 

> I feel like I should be updating test/e2e/bundle_e2e_test.go to add the new type to the tests, but I can't work out what makes the test bundle so I could add a ConsoleYamlSample to it. Any pointers?

We're in the middle of establishing a method of building test bundles on the fly across our different test environments (I'll try to hunt down some draft designs on this). For now, we use test bundle images hosted in quay.io.

**Comment by Jamstah** [comment]
> Sorry for the delayed response @Jamstah
> 
> > I feel like I should be updating test/e2e/bundle_e2e_test.go to add the new type to the tests, but I can't work out what makes the test bundle so I could add a ConsoleYamlSample to it. Any pointers?
> 
> We're in the middle of establishing a method of building test bundles on the fly across our different test environments (I'll try to hunt down some draft designs on this). For now, we use test bundle images hosted in quay.io that are, unfortunately, managed manually.

No worries.

So, is there something I should be doing to update those bundles to allow me to add to the tests here, or are you happy to not add tests for this?

**Comment by Jamstah** [comment]
What's next on this one?

**Comment by exdx** [comment]
/hold
some kind of issue with the bot

**Comment by exdx** [comment]
/hold 
CI issue

**Pull request merged**
