### PR TITLE
Add priorityClassName

### PR DESCRIPTION
**Pull request by jianzhangbjz**
Fix [bug 1685330](https://bugzilla.redhat.com/show_bug.cgi?id=1685330), move the `priorityClassName` attribute to right place.

### CODE REVIEW

**Comment by ecordell** [comment]
Thank you @jianzhangbjz! I had to regen the manifests (that get pulled into CVO)

**Comment by jianzhangbjz** [comment]
@ecordell Many thanks for your help! Did you make these changes manually? I tried to run `make release` to update that files, but many other files are changed. So, I canceled it.
```console
mac:operator-lifecycle-manager jianzhang$ make release
build flag -mod=vendor only valid when using modules
docker pull quay.io/operator-framework/olm:0.9.0
0.9.0: Pulling from operator-framework/olm
8e402f1a9c57: Already exists 
8566d34393bd: Already exists 
2261f5a30303: Already exists 
762fe78c97cb: Already exists 
Digest: sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
Status: Image is up to date for quay.io/operator-framework/olm:0.9.0
/Library/Developer/CommandLineTools/usr/bin/make target=upstream ver=0.9.0 quickstart=true package
build flag -mod=vendor only valid when using modules
yq w -i deploy/upstream/values.yaml olm.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/upstream/values.yaml catalog.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/upstream/values.yaml package.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
./scripts/package_release.sh 0.9.0 deploy/upstream/manifests/0.9.0 deploy/upstream/values.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_00-namespace.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_11-olm-operators.configmap.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_04-installplan.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_05-subscription.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_06-catalogsource.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_10-operatorgroup.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_09-aggregated.clusterrole.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_07-olm-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_08-catalog-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_18-upstream-operators.catalogsource.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_13-operatorgroup-default.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.vTv1sadD/chart/olm/templates/0000_50_olm_14-packageserver.subscription.yaml
ln -sfFn ./0.9.0 deploy/upstream/manifests/latest
./scripts/package_quickstart.sh deploy/upstream/manifests/0.9.0 deploy/upstream/quickstart/olm.yaml
Wrote manifest to deploy/upstream/quickstart/olm.yaml
/Library/Developer/CommandLineTools/usr/bin/make target=okd ver=0.9.0 package
build flag -mod=vendor only valid when using modules
yq w -i deploy/okd/values.yaml olm.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/okd/values.yaml catalog.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/okd/values.yaml package.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
./scripts/package_release.sh 0.9.0 deploy/okd/manifests/0.9.0 deploy/okd/values.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_00-namespace.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_11-olm-operators.configmap.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_04-installplan.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_05-subscription.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_06-catalogsource.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_10-operatorgroup.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_09-aggregated.clusterrole.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_07-olm-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_08-catalog-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_13-operatorgroup-default.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.M9v1oPCU/chart/olm/templates/0000_50_olm_14-packageserver.subscription.yaml
ln -sfFn ./0.9.0 deploy/okd/manifests/latest
/Library/Developer/CommandLineTools/usr/bin/make target=ocp ver=0.9.0 package
build flag -mod=vendor only valid when using modules
yq w -i deploy/ocp/values.yaml olm.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/ocp/values.yaml catalog.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
yq w -i deploy/ocp/values.yaml package.image.ref quay.io/operator-framework/olm@sha256:7e4b13b89b3d59876b228697bbd0c9e364fd73f946ab90308c34fd82053a5a76
./scripts/package_release.sh 0.9.0 deploy/ocp/manifests/0.9.0 deploy/ocp/values.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_00-namespace.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_11-olm-operators.configmap.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_04-installplan.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_05-subscription.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_06-catalogsource.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_10-operatorgroup.crd.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_09-aggregated.clusterrole.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_02-services.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_07-olm-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_08-catalog-operator.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_17-packageserver.deployment.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_15-operatorstatus.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_16-packageserver.clusterserviceversion.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/image-references
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_13-operatorgroup-default.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_19-service-monitor.yaml
wrote /var/folders/2c/4whhm34n7892mf9l2j02cf480000gn/T/tmp.sCG92JJI/chart/olm/templates/0000_50_olm_14-packageserver.subscription.yaml
ln -sfFn ./0.9.0 deploy/ocp/manifests/latest
rm -rf manifests
mkdir manifests
cp -R deploy/ocp/manifests/0.9.0/. manifests
find ./manifests -type f -exec sed -i '' -e "/^#/d" {} \;
find ./manifests -type f -exec sed -i '' -e "1{/---/d}" {} \;
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
sed: 1: "1{/---/d}
": extra characters at the end of d command
```
```git
mac:operator-lifecycle-manager jianzhang$ git status
On branch priority
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
	modified:   deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
	modified:   deploy/chart/templates/_packageserver.deployment-spec.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_07-olm-operator.deployment.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_08-catalog-operator.deployment.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_09-aggregated.clusterrole.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_11-olm-operators.configmap.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_16-packageserver.clusterserviceversion.yaml
	modified:   deploy/ocp/manifests/0.9.0/0000_50_olm_17-packageserver.deployment.yaml
	modified:   deploy/okd/manifests/0.9.0/0000_50_olm_09-aggregated.clusterrole.yaml
	modified:   deploy/upstream/manifests/0.9.0/0000_50_olm_09-aggregated.clusterrole.yaml
	modified:   deploy/upstream/quickstart/olm.yaml
	modified:   manifests/0000_50_olm_00-namespace.yaml
	modified:   manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
	modified:   manifests/0000_50_olm_02-services.yaml
	modified:   manifests/0000_50_olm_03-clusterserviceversion.crd.yaml
	modified:   manifests/0000_50_olm_04-installplan.crd.yaml
	modified:   manifests/0000_50_olm_05-subscription.crd.yaml
	modified:   manifests/0000_50_olm_06-catalogsource.crd.yaml
	modified:   manifests/0000_50_olm_07-olm-operator.deployment.yaml
	modified:   manifests/0000_50_olm_08-catalog-operator.deployment.yaml
	modified:   manifests/0000_50_olm_09-aggregated.clusterrole.yaml
	modified:   manifests/0000_50_olm_10-operatorgroup.crd.yaml
	modified:   manifests/0000_50_olm_11-olm-operators.configmap.yaml
	modified:   manifests/0000_50_olm_12-olm-operators.catalogsource.yaml
	modified:   manifests/0000_50_olm_13-operatorgroup-default.yaml
	modified:   manifests/0000_50_olm_14-packageserver.subscription.yaml
	modified:   manifests/0000_50_olm_15-operatorstatus.yaml
	modified:   manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
	modified:   manifests/0000_50_olm_17-packageserver.deployment.yaml
	modified:   manifests/0000_50_olm_19-service-monitor.yaml
	modified:   manifests/image-references
```
And, I don't know why the `find ./manifests -type f -exec sed -i '' -e "1{/---/d}" {} \;` command still failed on MacOS even if I added empty string: `''`.

**Comment by ecordell** [comment]
/retest

I ran the make release script like you did, but the syntax that we use for sed there is gnu sed, which is different from what ships by default on mac. If you update to gnu sed you'll find it generates correctly.

**Comment by jianzhangbjz** [comment]
`/test e2e-aws-olm`

**Comment by jianzhangbjz** [comment]
Thanks for your help! @ecordell @njhale

**Pull request merged**
