### PR TITLE
chore(deploy): change 30 prefix to 50

### PR DESCRIPTION
**Pull request by ecordell**

### CODE REVIEW

**Comment by njhale** [comment]
Looks like the old "30" run-level prefixed manifests are still in the ./manifests and ./deploy/*/manifests/8.0.1. directories.

**Comment by ecordell** [comment]
Nice catch - this wasn't deleting the old ones (the new ones were there though)

**Comment by wking** [comment]
[e2e-aws][1]:

```
failed: (2m5s) 2019-01-21T23:06:56 "[Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal]"
```

and other unrelated issues.

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/678/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/1012/build-log.txt

**Comment by wking** [comment]
[e2e-aws][1]:

```
failed: (2m51s) 2019-01-22T00:18:08 "[Feature:DeploymentConfig] deploymentconfigs with test deployments [Conformance] should run a deployment to completion and then scale to zero [Suite:openshift/conformance/parallel/minimal]"
```

and more.

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/678/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/1015/build-log.txt

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=warning msg="RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 68"
level=fatal msg="waiting for bootstrap-complete: timed out waiting for the condition"
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/678/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws/1016/build-log.txt

**Pull request merged**
