### PR TITLE
Retract v3.11.0+incompatible

### PR DESCRIPTION
**Pull request by janisz**
See: https://go.dev/ref/mod#go-mod-file-retract
Closes: #2253

### CODE REVIEW

**Comment by janisz** [comment]
cc: @porridge

**Review by porridge — APPROVED** [review]
/lgtm

I think this is better than [having every user explicitly ignore this version](https://github.com/dependabot/dependabot-core/issues/10339).

**Comment by kevinrizza** [comment]
this looks reasonable to me. I just started the tests

**Review by anik120 — APPROVED** [review]
/lgtm

**Pull request merged**
