### PR TITLE
fix name of dir - replace Documentation for doc

### PR DESCRIPTION
**Pull request by camilamacedo86**
## WHAT
- Rename the dir "Documentation" for "doc"

## WHY
- Following the org standard
- It should not start with uppercase.

### CODE REVIEW

**Comment by ecordell** [comment]
/approve
/lgtm

This is great - the only reason we had it `Documentation` in the first place was due to tooling requirements.

**Comment by ecordell** [comment]
/ok-to-test

sorry, I think we have a conflict from proposals that merged

**Comment by camilamacedo86** [comment]
Hi @ecordell,

It is rebased with the master now. Could we merge it now?

**Comment by camilamacedo86** [comment]
Hi @ecordell,

It is rebased with the master, could we merge it now?

**Comment by ecordell** [comment]
@camilamacedo86 It looks like your last pr causes a conflict with this one - would you mind rebasing?

**Comment by camilamacedo86** [comment]
Hi @ecordell done :-)

**Comment by ecordell** [comment]
doc only - merge

**Pull request merged**
