### PR TITLE
Bug 1809661: Update subscription_sync_count to include the package name

### PR DESCRIPTION
**Pull request by simrandhaliw**
**Description of the change:**
This PR updates the subscription_sync_count metric to include a packageName label.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by sdodson** [comment]
Please look into the unit test failures, they've never passed for this PR.

**Comment by suratsuriya** [comment]
surat0960077011@gmail.com

**Comment by anik120** [comment]
@sdodson @suratsuriya is there a way to pause the bot from retesting it temporarily?

**Comment by sdodson** [comment]
/hold
should do it

**Pull request merged**
