### PR TITLE
Bug 1821274: Add CSV Metadata to PackageManifests

### PR DESCRIPTION
**Pull request by awgreene**
Backports a couple of commits that add more CSV Metadata to packagemanifests.

### CODE REVIEW

**Comment by knobunc** [comment]
Untagged this because it is consistently failing tests with a chown error.

**Comment by bparees** [comment]
@awgreene needs rebase

**Comment by shawn-hurley** [comment]
@awgreene bump needs rebase

**Comment by sdodson** [comment]
@awgreene bump needs rebase

**Comment by sdodson** [comment]
/lgtm cancel
Rebasing would trigger this anyway, so get this off patch manager queue until it's been rebased.

**Pull request merged**
