### PR TITLE
cmd/catalog: Migrate to using cobra for CLI flag management

### PR DESCRIPTION
**Pull request by timflannagan**
Update the cmd/catalog/main.go and use cobra's CLI library for managing
CLI executables and parsing flags.

Introduce cmd/catalog/start.go which is responsible for returning a
populated command.Command structure that the main function can call and
execute.

Signed-off-by: timflannagan <timflannagan@gmail.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by perdasilva** [comment]
Do you think we should close https://github.com/operator-framework/operator-lifecycle-manager/pull/2524 - I think this PR should solve the issue I was running into as well (flag being redefined)...

**Comment by sathieu** [comment]
Hello,

Can OLM be released ?

The deployment is not updated but the image is, the catalog pod crashloopbackoff with:

```console
$ kubectl logs -n operator-lifecycle-manager catalog-operator-76b49b4678-hxbd2
Error: unknown shorthand flag: 'n' in -namespace
unknown shorthand flag: 'n' in -namespace
```

**Comment by timflannagan** [comment]
@sathieu Yup - we'll need to apply a new rendered deployment manifest. Let me check in with the team about cutting a new minor version release.

**Comment by timflannagan** [comment]
@sathieu It looks like the v0.21.0 release was just published (apologies for the delay).

**Comment by sathieu** [comment]
@timflannagan Thanks for the release.

**Pull request merged**
