### PR TITLE
BUG 1825349: Generation required bug

### PR DESCRIPTION
**Pull request by awgreene**
In the InstallPlan, the Generation field should not be required and may
be omitted.

Bugzilla Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1825349

### CODE REVIEW

**Comment by awgreene** [comment]
/retest
```TestDeleteInternalRegistryPodTriggersRecreation``` passes locally

**Comment by awgreene** [comment]
/test e2e-gcp

`ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource []`

**Comment by awgreene** [comment]
/test e2e-gcp
`ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource []`

**Comment by russellb** [comment]
@awgreene There are 3 commits in this PR, but only the first one seems related to the referenced bug.  Can you add some more clarity on the other changes?

It would be really helpful to have a lot more detail in each commit message.  For example, the other 2 commits only have a 1 line commit message and they don't do much to explain why the change was being made, so I'm having a hard time determining whether allowing those changes to be included is appropriate.

Thanks!

**Comment by awgreene** [comment]
Good question @russellb

>@awgreene There are 3 commits in this PR, but only the first one seems related to the referenced bug. Can you add some more clarity on the other changes?

Sure - let's review the commits:
1. As you said, the first commit is the fix for the bug mentioned in the BZ.
2. The second commit updates an e2e test that would always fail because an image that the test relied on was updated.
3. The third updates an e2e test that was experiencing an extremely high failure rate - preventing bug fixes from getting into 4.4.

**Pull request merged**
