### PR TITLE
Dockerfile: Avoid hardcoding the kubebuilder version in the build root image

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**
Update the build root Dockerfile and add an argument for the kubebuilder version, and avoid hardcoding the version when curling that binary into $PATH.

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
These changes are quite literally a no-op, so I'm going to override that e2e-aws test.

/override ci/prow/e2e-aws-olm

**Pull request merged**
