### PR TITLE
Cut Release 0.9.0

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Continued release process from https://github.com/operator-framework/operator-lifecycle-manager/pull/801 to include new `apiVersions`.

Addresses https://jira.coreos.com/browse/OLM-1017

### CODE REVIEW

**Comment by njhale** [comment]
@alecmerdler nice! Could you update the `CHANGELOG.md` before you generate a new release on Github? You can include it as a followup commit or PR.

You can use [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator) to generate the updated `CHANGELOG.md` in a single command: ` github_changelog_generator -u operator-framework -p operator-lifecycle-manager --since-tag=0.4.0 --token=<your-gh-api-token> --future-release=9.0.0 --pr-label="**Other changes:**"`

**Comment by alecmerdler** [comment]
@njhale Fought with `github-changelog-generator` too much, we can add it in a followup PR.

**Comment by cmoulliard** [comment]
When is it planned to release it ?

**Pull request merged**
