### PR TITLE
add logo for github dark theme

### PR DESCRIPTION
**Pull request by eliranmal**
**Description of the change:**

in the repository's main readme file, support github's dark theme by adding a new image, and using the appropriate suffix for the image URLs.

here's a screenshot demonstrating the proposed solution, with the dark-dimmed theme:

Screen Shot 2022-02-12 at 3 11 54

&hellip; and another one, showing there's no regression with a light theme on:

Screen Shot 2022-02-12 at 3 12 23

**Motivation for the change:**

currently, when github users switch to dark mode, the logo text disappears into the background (to a certain extent, depending on the specific theme variant).

see screenshots of the current state in the reported issue (#2623).

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

Closes: #2623

### CODE REVIEW

**Comment by njhale** [comment]
@eliranmal Wow, that's much better! Thank you for taking the time to help make the repo look more professional!

It looks like you've yet to sign off on the commit -- if you amend the `--sign-off` flag and push, we should be able to get this merged quickly.

/approve

**Comment by eliranmal** [comment]
thanx @njhale ! that was quick

yes, i was reading through the docs, and it just bugged me 😄 

i did amend my (single) commit to contain the sign-off line, but i'll double check (maybe i pushed two separate commits, and one of them is faulty...).

**Comment by eliranmal** [comment]
done! turns out my IDE messed it up :)

**Review by timflannagan — APPROVED** [review]

**Comment by eliranmal** [comment]
thanx! 🎂

**Pull request merged**
