### PR TITLE
Use of/gini instead of inifrance/gini

### PR DESCRIPTION
**Pull request by kevinrizza**
The github.com/irifrance/gini package has been purged from github. An existing version that preserved that history has been forked to the operator-framework org, and this commit updates that dependency to use the forked version.

In the future, we should investigate https://github.com/go-air/gini if and when it creates consumable releases, as it appears that the maintainer of the missing package is now maintaining the package there.

Resolves https://github.com/operator-framework/operator-lifecycle-manager/issues/2322

### CODE REVIEW

**Comment by timflannagan** [comment]
Interesting:

```
--- FAIL: TestSyncOperatorGroups (1.45s)
    --- FAIL: TestSyncOperatorGroups/AllNamespaces/CSVPresent/InstallModeNotSupported (0.16s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11577b9]
```

**Comment by timflannagan** [comment]
It looks like there's some ordering that `go mod tidy` is complaining about that's failing the verification check. Likely just need to re-run that command and re-commit.

**Comment by kevinrizza** [comment]
@timflannagan should be fixed now

**Pull request merged**
