### PR TITLE
Bug 1889838: fix race in Operator reconcilation

### PR DESCRIPTION
**Pull request by sjenning**
xref https://bugzilla.redhat.com/show_bug.cgi?id=1889838

Fixes race in Operator reconciliation that causes unit test flake introduced by https://github.com/operator-framework/operator-lifecycle-manager/pull/1816

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/1822/pull-ci-operator-framework-operator-lifecycle-manager-release-4.6-unit/1318548827241713664

@njhale @ecordell

### CODE REVIEW

**Comment by sjenning** [comment]
checking for flake
/test unit

**Comment by sjenning** [comment]
5 green units tests runs in a row.  Looks to have resolved the issue.

**Comment by njhale** [comment]
/approve

Just waiting on an LGTM now.

**Review by awgreene — COMMENTED** [review]
/lgtm

**Pull request merged**
