### PR TITLE
[release-4.6] Bug 1945149: only override deployment resources when explicitly defined in subscription config

### PR DESCRIPTION
**Pull request by joelanford**
Manual cherry pick of #2036

### CODE REVIEW

**Comment by joelanford** [comment]
/hold

I need to backport the `operator-framework/api` component of this PR to the (currently non-existent) v0.3.x branch and cut a new release. Just want to let CI run to make sure the entire patch set works.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.


* Score: *0.20*
* Reason: *maximum total for this z-stream is 10*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Pull request merged**
