### PR TITLE
vendor: re-run `dep ensure`

### LINKED ISSUE #389: make schema-check fails with missing vendored dependency
steps to reproduce:

1. git clone
2. set gopath
3. make schema-check

```
go run ./cmd/validator/main.go ./deploy/chart/catalog_resources
vendor/github.com/emicklei/go-restful/container.go:17:2: cannot find package "github.com/emicklei/go-restful/log" in any of:
	/Users/jzelinskie/CoreOS/go/olm/src/github.com/operator-framework/operator-lifecycle-manager/vendor/github.com/emicklei/go-restful/log (vendor tree)
	/usr/local/opt/go/libexec/src/github.com/emicklei/go-restful/log (from $GOROOT)
	/Users/jzelinskie/CoreOS/go/olm/src/github.com/emicklei/go-restful/log (from $GOPATH)
make: *** [schema-check] Error 1
```

### PR DESCRIPTION
**Pull request by jzelinskie**
This captures the subpackage `log` from github.com/emicklei/go-restful

Fixes #389.

### CODE REVIEW

**Comment by ecordell** [comment]
Is this dependency real? It looks like maybe a bad goimports and it was supposed to be logrus (aliased to log)

**Comment by jzelinskie** [comment]
Doesn't look like it to me, the go-restful library uses it and something depends on that.

**Comment by ecordell** [comment]
@jzelinskie do you have an older version of dep? The diff removes a ton of metadata from the gopkg.lock

**Comment by jzelinskie** [comment]
I have the latest release

**Pull request merged**
