### PR TITLE
GitHub Actions Updates

### PR DESCRIPTION
**Pull request by dtfranz**
Updates our github action versions for future proofing and to silence deprecation warnings.

### CODE REVIEW

**Comment by dtfranz** [comment]
/hold 
Until actions health can be verified.

**Comment by dtfranz** [comment]
/unhold
Actions appear to be unaffected and the deprecation warnings are gone :)

**Review by tmshort — APPROVED** [review]
/lgtm

**Review by perdasilva — APPROVED** [review]
lgtm

**Pull request merged**
