### PR TITLE
Fix the subscription annotation

### PR DESCRIPTION
**Pull request by SchSeba**
generating invalid metadata.Labels for an already adopted Subscription resource

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by kevinrizza** [comment]
Removed ocp bug prefix, since this is the upstream repository
/ok-to-test

**Comment by SchSeba** [comment]
@kevinrizza is the failing a flake? or something my PR breaks

**Comment by SchSeba** [comment]
Hi @dinhxuanvu @timflannagan any update on this PR?

**Comment by timflannagan** [comment]
@SchSeba Apologies for the slow replies - our upstream e2e runs have been fairly red this past month, so that's been our focus. I can take a look at these changes today.

**Comment by SchSeba** [comment]
Hi @timflannagan any update on this PR?

do you want me to close it if you think is not necessary ?

**Comment by perdasilva** [comment]
Closing in favor of #2447 2731

**Pull request closed without merging**
