### PR TITLE
fix(run_console_loca): Fix command and improve output message

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
https://github.com/operator-framework/operator-lifecycle-manager/issues/785

## What
- Fix the script
- Improve output to make clear for the users the URL to check OLM console locally
- Add make command
- Update the readme in order to recommend the usage of the README

## Additional
Following how it will appear when an error is faced.
(The most common scenario is when the OLM is already running)

Screenshot 2019-05-13 at 09 27 05

### CODE REVIEW

**Comment by camilamacedo86** [comment]
c/c @ecordell

**Comment by ecordell** [comment]
Thanks @camilamacedo86! 

/ok-to-test

**Comment by camilamacedo86** [comment]
Hi @ecordell, 

Could we re-run the test `https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/858/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws-upgrade/205`. It shows not have a relation with the change. Could you help me with?

**Pull request merged**
