### PR TITLE
BUG 1825349: Generation should not be a required field

### PR DESCRIPTION
**Pull request by awgreene**
In the InstallPlan, the Generation field should not be required and may
be omitted.

Bugzilla Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1825349

### CODE REVIEW

**Comment by awgreene** [comment]
Pulled in a commit that @exdx added to improve e2e stability.

**Comment by benluddy** [comment]
/retest

> {"command":"git fetch https://github.com/operator-framework/operator-lifecycle-manager.git --tags --prune","component":"clonerefs","error":"exit status 128","file":"prow/pod-utils/clone/clone.go:57","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"fatal: unable to access 'https://github.com/operator-framework/operator-lifecycle-manager.git/': The requested URL returned error: 504\n","time":"2020-04-21T15:33:46Z"}
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/1467/pull-ci-operator-framework-operator-lifecycle-manager-release-4.4-images/38#1:build-log.txt%3A60

**Comment by awgreene** [comment]
Git outtage is preventing me from updating this PR. Closing in favor of https://github.com/operator-framework/operator-lifecycle-manager/pull/1473

**Pull request closed without merging**
