### PR TITLE
Updates github.com/operator-framework/api

### PR DESCRIPTION
**Pull request by m1kola**
**Description of the change:**

Updates OLM to use a new release of `github.com/operator-framework/api` which includes several changes which are prerequisites for the following changes:
* https://github.com/operator-framework/operator-lifecycle-manager/pull/2942 requires new condition types.
* https://github.com/operator-framework/operator-lifecycle-manager/pull/2959 which also requires a constant defined in the api package so we can switch to using it instead of defining it in the OLM codebase.

**Motivation for the change:**

Solving prerequisites for other changes.

**Architectural changes:**

Updating dependencies

**Testing remarks:**

Refactoring. Existing tests should provide coverage.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by m1kola** [comment]
CI is red because packageserver fails with the following error (not visible in CI logs):

> unable to get openapi models: cannot find model definition for github.com/operator-framework/api/pkg/operators/v1alpha1.APIResourceReference. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again

Trying to fix it here: https://github.com/operator-framework/api/pull/168

**Review by tmshort — APPROVED** [review]
LGTM, but I'd like to see another review (with the /lgtm)

**Pull request merged**
