### PR TITLE
[release-4.5] Bug 1882444: remove extra polling check 

### PR DESCRIPTION
**Pull request by exdx**
**Description of the change:**
Backport of #1773 

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by exdx** [comment]
/hold
depends on #1765 merging first

**Pull request merged**
