### PR TITLE
chore: update dependency github actions versions

### PR DESCRIPTION
**Pull request by perdasilva**
**Description of the change:**
actions/checkout@v3 -> @v4
actions/setup-go@v4 -> @v5
actions/upload-artifact@v3 -> @v3

**Motivation for the change:**
Warnings like: 
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-go@v4, actions/upload-artifact@v3`

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by itroyano** [comment]
Hi @perdasilva,

Adding a .github/dependabot.yml with the following example configuration, should help remove the need for this chore -

```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
```

in addition the same file can also have dependabot config to take care of go.mod

```
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
```

**Comment by perdasilva** [comment]
Ooohhh thank you!!!!

**Comment by itroyano** [comment]
Note you'll still need to review the PRs opened by Dependabot,  but it's very capable of rebasing and doing lots of stuff on its own.

**Comment by perdasilva** [comment]
closing in favor of #3226

**Pull request closed without merging**
