### PR TITLE
[release-4.1] Bug 1791850: Removing license year

### PR DESCRIPTION
**Pull request by Bowenislandsong**
this commit removes the license year from code base and unblocks PRs that fails on the verify test.

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ashcrow** [comment]
This does not look like a must have 4.1 fix.

**Comment by Bowenislandsong** [comment]
> This does not look like a must have 4.1 fix.

It is a must have and it is blocking all backports to 4.1

**Comment by bparees** [comment]
We currently see no reason to do a 4.1.z release just to pick up this PR.  If we have a critical fix for 4.1 in the future, we can consider including this PR at that point in time.

**Comment by ecordell** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/pull/1312 needs to merge in 4.1 and is currently blocked on CI due to this PR.

**Comment by dinhxuanvu** [comment]
This licensing PR currently blocks this CVE run-level PR: https://github.com/operator-framework/operator-lifecycle-manager/pull/1312

**Comment by sdodson** [comment]
> This licensing PR currently blocks this CVE run-level PR: #1312

I'll pull this in but I think the proper way to have addressed this is to simply have included this commit in #1312

**Comment by sdodson** [comment]
(sorry, this has to wait until tomorrow anyway)

**Pull request merged**
