### PR TITLE
(doc) How to update operators documentation

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vdinh@redhat.com>

### CODE REVIEW

**Comment by mhrivnak** [comment]
Can we move this forward soon and get it merged? I would like to contribute additional docs about z-stream management before I forget what we settled on; that'll be a lot easier with this in-place. Thanks!

**Comment by dinhxuanvu** [comment]
I will get this PR updated to address some of the feedbacks and will get it moving forward and merged soon. Thanks.

**Comment by ecordell** [comment]
Quick note - docs now live in `/docs`, so these should be moved as well.

**Comment by ecordell** [comment]
doc-only, merging

**Pull request merged**
