### PR TITLE
remove minishift support

### PR DESCRIPTION
**Pull request by leseb**
As per #705 (comment) it has been decided to drop support for minishift.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by njhale** [comment]
@leseb These are good changes, but as we discussed in #705 we want to move away from minishift altogether. `make run-local` uses minikube and builds with `upstream.Dockerfile` which copies the required git objects into the image. If we can repurpose this PR to remove the minishift stuff, that would be incredibly helpful - up to you.

**Comment by leseb** [comment]
@njhale done!

**Comment by ecordell** [comment]
@leseb - we intentionally omitted the git objects to limit the size of our build context. Is there a reason you need or want a full git repo inside of the image?

**Comment by leseb** [comment]
@ecordell I haven't tried again without minishift so I was just assuming this bug was on the other Dockerfile too. Thanks for commenting, let me remove that commit then.

**Comment by ecordell** [comment]
Thanks for this! Could you also remove `e2e-local-shift` from the Makefile?

/approve

**Comment by leseb** [comment]
@njhale done!

**Comment by leseb** [comment]
I believe CI's failure is unrelated to that patch, isn't?

**Pull request merged**
