### PR TITLE
fix: grpc connections

### PR DESCRIPTION
**Pull request by exdx**
**Description of the change:**
Builds off of #2333 

**Motivation for the change:**
Improve gRPC connection performance, particularly in e2e test scenarios 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by exdx** [comment]
Aside from the unit test failures, this seems to hit the IDLE problem where the catalog source pod sits in an IDLE state instead of going to READY
```
waiting for catalog pod mock-ocs-main-hdz7m to be available (after catalog update) - IDLE
```
https://github.com/operator-framework/operator-lifecycle-manager/pull/2386/checks?check_run_id=3792136502

**Review by tylerslaton — COMMENTED** [review]
Just a few questions and potential suggestions!

**Comment by exdx** [comment]
Related to #1186

**Comment by timflannagan** [comment]
Closing as this is fairly stale at this point and needs to be rebased. It looks like there's some issues we'll need to weed out with the newer grpc version bump anyways, but at least that's tracked in the existing issue.

**Pull request closed without merging**
