### PR TITLE
Add Visibility Label for Included CatalogSources

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Used as a solution to filtering out `CatalogSources` created by Marketplace Operator for the OperatorHub UI.

### CODE REVIEW

**Comment by ecordell** [comment]
Why is this needed? If the global namespace is `openshift-marketplace`, then olm-operators will only be visible when you directly to openshift-operator-lifecycle-manager.

**Comment by alecmerdler** [comment]
@ecordell The only label selector which will filter "installed" `CatalogSources` (from Marketplace Operator), but keep the "app registry" ones is `olm-visibility: Exists`. Which means any `CatalogSources` we want to be visible in OperatorHub need to have this label.

**Comment by alecmerdler** [comment]
@njhale Does this look good to you?

**Comment by alecmerdler** [comment]
Is there a `labelSelector` that will satisfy the filter requirements for the following `CatalogSources`?

**"Installed" `CatalogSource` (hide):**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    csc-owner-name: installed-community-olm-dev-old
    csc-owner-namespace: openshift-marketplace
  name: installed-community-olm-dev-old
  uid: 8d06d8b9-87be-11e9-aeff-021ae8451416
spec:
 ...
status:
  ...
```
**"OCP Included" `CatalogSource` (show):**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    csc-owner-name: certified-operators
    csc-owner-namespace: openshift-marketplace
    olm-visibility: hidden
    openshift-marketplace: 'true'
    opsrc-datastore: 'true'
    opsrc-owner-name: certified-operators
    opsrc-owner-namespace: openshift-marketplace
    opsrc-provider: certified
  name: certified-operators
spec:
  ...
status:
  ...
```
**"OperatorHub.io" `CatalogSource` (show):**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
spec:
  ...
```

**Comment by ecordell** [comment]
What about:

hide if:
```
csc.owner.name && !openshift-marketplace
```
?

**Comment by alecmerdler** [comment]
Label selectors are for _matching_ expressions to include, not exclude. The negation of that would be:
```
csc-owner-name: DoesNotExist || openshift-marketplace: Exists
```
Like I said, you can't do OR statements :cry:

**Comment by aravindhp** [comment]
If only [set based requirements](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements) worked for CRDs...

**Comment by ecordell** [comment]
How difficult would it be to make two api calls? `openshift-marketplace=true` and `!csc-owner-name` should find everything we want to display?

**Comment by galletti94** [comment]
In the installation of an operator you could set the `openshift-marketplace` label to `false`. Then your label selector would just be based on that label's value? From what I remember, this was the original intent of that label.

**Comment by galletti94** [comment]
Nvm I just saw your comment about exclusion.

**Comment by alecmerdler** [comment]
Ended up [using two queries for `PackageManifest`](https://github.com/openshift/console/pull/1627/files#diff-678de420ac7711f131c2d103e91e969fR101): one for Marketplace items and another for local `CatalogSources`.

**Pull request closed without merging**
