### PR TITLE
Bug 1912565: update moby/term dependency

### PR DESCRIPTION
**Pull request by exdx**
**Description of the change:**
Updates the indirect moby/term dependency to a newer version due to the following error on macOS only when running commands like `make run-local` and `make unit`
```
vendor/github.com/docker/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
# github.com/moby/term
vendor/github.com/moby/term/tc.go:13:28: undefined: unix.SYS_IOCTL
vendor/github.com/moby/term/tc.go:18:28: undefined: unix.SYS_IOCTL
vendor/github.com/moby/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
vendor/github.com/moby/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
```
The docker term library attempts to make syscalls directly, which is not supported in recent versions of macOS. 
See https://github.com/ory/dockertest/issues/212 for more info

Note: you can update a transitive dependency without using replaces so long as the version is compatible via the go tool. 

>  As part of maintaining the require statements in go.mod, the go command tracks which ones provide packages imported directly by the current module and which ones provide packages only used indirectly by other module dependencies. Requirements needed only for indirect uses are marked with a "// indirect" comment in the go.mod file. Indirect requirements are automatically removed from the go.mod file once they are implied by other direct requirements. Indirect requirements only arise when using modules that fail to state some of their own dependencies or when explicitly upgrading a module's dependencies ahead of its own stated requirements.

**Motivation for the change:**
Fixes broken local testing on macOS 

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by exdx** [comment]
rebased off 1.20 bump

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by benluddy** [comment]
/hold

Can we pin `github.com/moby/term` instead?

**Pull request merged**
