### PR TITLE
[release-4.1] Bug 1820339: Update subscription_sync_count to include the package label

### PR DESCRIPTION
**Pull request by simrandhaliw**
**Description of the change:**
This PR updates the subscription_sync_count metric to include a packageName label.

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by spadgett** [comment]
Console test fix in openshift/console#5058

**Comment by eparis** [comment]
Can you help me understand why this is absolutely critical to fix 4.1? Should we just close this and the bug?

**Comment by russellb** [comment]
@simrandhaliw @ecordell  Please see the comment from @eparis from last week.  We'll need to discuss whether this is appropriate for 4.1.

> Can you help me understand why this is absolutely critical to fix 4.1? Should we just close this and the bug?

**Comment by russellb** [comment]
/hold

until discussion is complete on whether this should mege

**Comment by ecordell** [comment]
Since 4.1 is out of support, closing.

**Pull request closed without merging**
