### PR TITLE
Don't use $BUILDPLATFORM image for goreleaser

### PR DESCRIPTION
**Pull request by StopMotionCuber**
**Description of the change:** Removes the `--platform=$BUILDPLATFORM` argument

**Motivation for the change:** When specifying the platform as $BUILDPLATFORM, amd64 binaries are taken. This leads to the image not being multi-arch, but still having an amd64 busybox binary.
The [util init container](https://github.com/operator-framework/operator-lifecycle-manager/blob/67177c0c822fbe7d554669262c6b4f54bebad17f/pkg/controller/bundle/bundle_unpacker_test.go#L267) of jobs are failing with an `exec /bin/cp: exec format error`.

**Architectural changes:** None

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

Further remarks: I already opened #2890 to increase multi-arch/arm64 compatibility. In case wanted, I can also incorporate this change into that PR

### CODE REVIEW

**Comment by risaraf** [comment]
Any updates on this? This is blocking us from using OLM on ARM.

**Comment by StopMotionCuber** [comment]
Have rebased the branch and added a sign-off to make it compliant with the DCO policy in the repo, would like to see it get merged

**Review by dmesser — APPROVED** [review]

**Comment by aimichelle** [comment]
Thanks for pulling this in! @dmesser , do you know when this might be released? We're excited to start running OLM in ARM. :)

**Comment by risaraf** [comment]
Can we get a minor version release with this fix?

**Comment by awgreene** [comment]
Released v0.24.0

**Pull request merged**
