### PR TITLE
Doc: Remove legacy webhook proposal

### PR DESCRIPTION
**Pull request by awgreene**
The Webhook proposal has been moved to the
operator-framework/enhancement repository in a recent PR [1]. This
commit removes a legacy proposal that exists in the olm repository.

Ref:
[1] https://github.com/operator-framework/enhancements/pull/9

### CODE REVIEW

**Comment by ecordell** [comment]
Can we leave a placeholder with a link to the new doc, for people that have saved links to this one?

**Comment by awgreene** [comment]
@ecordell addressed your comment.

**Comment by ecordell** [comment]
/lgtm
/approve

doc-only

**Pull request merged**
