### PR TITLE
Bug 1738684: Update rh-operators configmap to prometheus 0.23.2

### PR DESCRIPTION
**Pull request by madorn**
Per @sichvoge, update rh-operators configmap to prometheus 0.23.2 for olm tech-preview on 3.11. Successful Installation on 3.11 cluster with OLM 0.7.1 and 0.7.2 has been tested/verified.

/hold @sichvoge please review. Once approved, I will add for olm 0.7.1, 0.7.4, and 0.8.0.

### CODE REVIEW

**Comment by sichvoge** [comment]
This is only available for 3.11 right?

**Comment by madorn** [comment]
> This is only available for 3.11 right?

as far as I know. @ecordell @njhale may be able to confirm.

**Comment by s-urbaniak** [comment]
cc @brancz for a final pass

**Comment by ecordell** [comment]
@madorn Actually getting these changes into 3.11 requires a PR against openshift-ansible to update the configmaps there.

**Comment by madorn** [comment]
@sichvoge Closing this PR. See https://github.com/openshift/openshift-ansible/pull/12092

**Pull request closed without merging**
