### PR TITLE
Bug 1791852: [release-4.3] Update license year

### PR DESCRIPTION
**Pull request by Bowenislandsong**
This commit updates the license year. The commit will unblock all pending PRs that are stuck with the verify test.

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by Bowenislandsong** [comment]
@operator-framework/patch-managers Could I get help to skip bugzilla + cherry-pick labels and merge this license year update PR? Thank you!

**Comment by crawford** [comment]
Copyright years listed in source aren't generally updated after creation; certainly not in a release branch.

**Pull request closed without merging**
