### PR TITLE
Bug 1791850: [release-4.1] Update license year

### PR DESCRIPTION
**Pull request by Bowenislandsong**
this commit updates the license year from 2019 to 2020 and unblocks PRs that fails on the verify test.

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by Bowenislandsong** [comment]
@operator-framework/patch-managers Could I get help to skip bugzilla + cherry-pick labels and merge this license year update PR? Thank you!

**Comment by Bowenislandsong** [comment]
v

**Comment by crawford** [comment]
Copyright years listed in source aren't generally updated after creation; certainly not in a release branch.

**Pull request closed without merging**
