### PR TITLE
Add CRD to "View" RBAC Role

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

When creating the "view" `Role` for instances of a custom resource, add the CRD itself so users can fetch the validation and additional printer columns.

Addresses https://jira.coreos.com/browse/ALM-785

### CODE REVIEW

**Comment by ecordell** [comment]
This looks good, we should support apiservices as well! I'm about to push up a PR that adds the pluralname to apiservicedefinitions in the CSV so that we can construct the RBAC for it

**Comment by alecmerdler** [comment]
@ecordell Is this blocked by #571?

**Comment by ecordell** [comment]
This is included in #618

**Pull request closed without merging**
