### PR TITLE
Bug 1805570: Remove run-level 1 from olm and openshift-operators namespaces

### PR DESCRIPTION
**Pull request by dinhxuanvu**
OLM and the operators that it deploys shouldn't have run-level 1
and should use SCC as "anyuid" or "restricted".

Signed-off-by: Vu Dinh <vdinh@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by ecordell** [comment]
/lgtm
/approve

If e2e passes this should be good.

**Comment by dinhxuanvu** [comment]
The removal of `run-level="1"` seems to cause some failures on `TestUpdateCSVInPlace` test case. For some reason, when the CSV was updated, the new pod failed to get deployed with this error: `**Error: error creating self-signed certificates: mkdir apiserver.local.config: permission denied**`.
Also, this test case uses a custom-built image `quay.io/coreos/mock-extension-apiserver:master` that is potentially not playing well with the new restricted setup.

**Comment by njhale** [comment]
I suspect that we just need to add the correct permissions in the [Dockerfile](https://github.com/operator-framework/mock-extension-apiserver/blob/master/Dockerfile) for the arbitrary user to have access; eg:

```Dockerfile
RUN chmod g=u /
USER 1001
```

**Comment by dinhxuanvu** [comment]
I manage to overcome the certificate issue but now another error pops up:
`W0225 05:44:06.564842       1 authentication.go:245] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
Error: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:openshift-operators:default" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

**Comment by dinhxuanvu** [comment]
Please keep this PR on hold until further notice on @shawn-hurley request. Thanks.

**Comment by dinhxuanvu** [comment]
Please hold for Shawn.
/hold

**Pull request merged**
