### PR TITLE
clean-up: add dependabot

### PR DESCRIPTION
**Pull request by perdasilva**
**Description of the change:**
Adds dependabot configuration to .github that will submit update PRs on a weekly basis to update go mod dependencies as well as github actions

**Motivation for the change:**

**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

### CODE REVIEW

**Comment by tmshort** [comment]
I thought we already had this? e.g.
https://github.com/operator-framework/operator-lifecycle-manager/pull/3205
Is this just configuration?

**Comment by itroyano** [comment]
That's a bit confusing @tmshort because I don't see a dependabot.yml in this repo.  I see it in OLM v1 repo though.

**Comment by perdasilva** [comment]
I think only security updates are enabled. I figured it would be good to have a configuration file anyway to keep it all as code.

**Review by joelanford — APPROVED** [review]

**Review by grokspawn — APPROVED** [review]

**Pull request merged**
