### PR TITLE
Bug 1758008: Manual approval strategy ignored for subsequent releases

### PR DESCRIPTION
**Pull request by dinhxuanvu**
For an subscription with manual approval, only the initial installplan
respects the approval requires. Subsequent installplans ignore the
fact the approval status is still false and install the operator
regardless. This issue is due to catalog incorrectly transitions
the installplan into install phase without checking for approval
condition.

Signed-off-by: Vu Dinh <vdinh@redhat.com>

**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [x] Docs updated or added to `/docs` 
- [x] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
PTAL

**Comment by ecordell** [comment]
@dinhxuanvu The fix looks good - can you write a test for this so we don't regress?

**Comment by ecordell** [comment]
@dinhxuanvu Can this be triggered with an e2e test similar to the ones testing the OperatorGroup serviceaccount scope?

i.e. create a manual installplan that would fail because of scope, then give the operatorgroup enough permission to install it, and then see it install anyway (even though it's manual)?

**Comment by dinhxuanvu** [comment]
Test case included. @ecordell Ready for final review.

**Pull request merged**
