### PR TITLE
update 'CSV copy watching all namespaces' case

### PR DESCRIPTION
**Pull request by jianzhangbjz**
The `CSV copy watching all namespaces` case updated the `global-operators` ConfigMap of `openshift-operators` to `signalNamespace` to watch if other namespaces' CSV is removed, but this `global-operators` ConfigMap will be recovered by CVO every 15 mins, it will lead case failure sometime. In this PR, we used a ConfigMap called global-operators to watch all namespaces in a newly created namespace.
Addressed https://github.com/openshift/operator-framework-olm/pull/368#issuecomment-1484692104

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Hi @perdasilva , could you help approve it? Thanks!
/assign @perdasilva

**Comment by jianzhangbjz** [comment]
Hi @awgreene , could you help have a review when you get a chance? Thanks!
/assign @awgreene

**Review by perdasilva — APPROVED** [review]
lgtm

**Comment by awgreene** [comment]
No longer necessary given https://github.com/operator-framework/operator-lifecycle-manager/pull/3042

**Pull request closed without merging**
