### PR TITLE
feat(build): allow skipping minikube during local builds

### PR DESCRIPTION
**Pull request by jpeeler**
This only changes behavior if the NO_MINIKUBE variable is set, otherwise minikube calls will be done exactly as before. (This probably only helps me out, but I'd really appreciate not having to comment out lines or apply a patch for each new branch I work on!)

### CODE REVIEW

**Comment by njhale** [comment]
Is the aim of this to avoid calling `minikube start...` again?

**Comment by njhale** [comment]
What does your test flow look like then? Do you end up using the `olm-e2e` image?

**Comment by jpeeler** [comment]
Yes, I use the olm-e2e image. Everything happens locally on my machine and nothing happens in a VM. I just set up my cluster beforehand and set the appropriate environment variables. (I use https://direnv.net  to manage the collection of environment variables based on the directory I'm in too.)

**Comment by jpeeler** [comment]
Actually, I've been using the e2e-local target which ultimately ends up executing go test directly. But it looks like there's a docker target that can use the olm-e2e image.

I'm asking that this get merged so that I can stop patching every local e2e I run. If others could benefit from a similar workflow, I don't mind working on adding some helper scripts to get a cluster easily running using the upstream hack script later on.

**Pull request merged**
