### PR TITLE
.github/workflows: Enable GH action that retests failed workflows

### PR DESCRIPTION
**Pull request by timflannagan**
**Description of the change:**

**Motivation for the change:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

### CODE REVIEW

**Comment by timflannagan** [comment]
Note: we already merged this in the operator-registry repository, and this needs to be merged first before we can get those command(s) working.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
