### PR TITLE
Disable clusteroperator for package server

### PR DESCRIPTION
**Pull request by tkashem**
Disable clusteroperator for package server while we fix https://bugzilla.redhat.com/show_bug.cgi?id=1723818.

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is likely to fail upgrade because it leaves a stranded operator version.

I would recommend reverting the change that broke the upgrade rather than completely disabling the operator (which is likely to break others who depend on it for testing)

**Comment by smarterclayton** [comment]
(If this doesn’t fail upgrade tests that’s probably a bug in the upgrade tests...)

**Comment by tkashem** [comment]
> This is likely to fail upgrade because it leaves a stranded operator version.
> 
> I would recommend reverting the change that broke the upgrade rather than completely disabling the operator (which is likely to break others who depend on it for testing)

@smarterclayton We have recently introduced this `clusteroperator` resource to track the deployment progress of `packageserver` component within olm. I don't believe this `clusteroperator` resource would exist in a 4.1 cluster.
No other test is depending on this newly introduced clusteroperator object yet, I believe.

I can definitely revert the PR that that introduced this clusteroperator object as well if that is desired. But I think it would have the same effect.

**Comment by smarterclayton** [comment]
Upgrade tests run against both 4.1 and recent builds of 4.2, so the e2e-aws-upgrade job should be failing because you removed an operator it knows about

**Comment by ecordell** [comment]
Keeping this staged just in case, but #925 should have fixed the underlying bug, making this unnecessary.

**Comment by ecordell** [comment]
Fixed the underlying issue

**Pull request closed without merging**
