### PR TITLE
fix(deploy): yaml error in imagereferences

### PR DESCRIPTION
**Pull request by ecordell**

### CODE REVIEW

**Comment by ironcladlou** [comment]
There's a new error here:

```
error: unable to upload new layer (0): Patch https://registry.svc.ci.openshift.org/v2/ci-op-6kznq9bx/release/blobs/uploads/1b2c98b3-e698-403d-878a-10d665f21285?_state=wlp-kk2la7vnJ1aRDpv7S0evI0psQd7odQ516LLvwEl7Ik5hbWUiOiJjaS1vcC02a3pucTlieC9yZWxlYXNlIiwiVVVJRCI6IjFiMmM5OGIzLWU2OTgtNDAzZC04NzhhLTEwZDY2NWYyMTI4NSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxOC0wOS0yNlQyMzoxMzoyMy41NjY4MTgxNzVaIn0%3D: operator "catalog" failed to map images: requested mapping for "quay.io/coreos/package-server@sha256:cc18b5711fb2126329c969f077f67f41981c87f800f6b2ceae5981422c14917b", but no input image could be located
```

**Comment by wking** [comment]
GitLab has issues, but everything else is green.

**Pull request merged**
