### PR TITLE
Bug 1818851: feat(catalogs): add spec validation for sourcetypes

### PR DESCRIPTION
**Pull request by benluddy**
Backport of error messaging changes from https://github.com/operator-framework/operator-lifecycle-manager/pull/1428.

### CODE REVIEW

**Comment by njhale** [comment]
/approve

At a glance, I think the error on the console test could be due to an overspecified expectation: https://github.com/openshift/console/blob/9d9397269afa57fd460aa87c73cc5e946f7e88d2/frontend/packages/operator-lifecycle-manager/integration-tests/scenarios/single-installmode.scenario.ts#L23

**Comment by sdodson** [comment]
/retitle Bug 1818851: feat(catalogs): add spec validation for sourcetypes

**Pull request merged**
