### PR TITLE
Revert "Merge pull request #788 from njhale/back-support-pkgs"

### PR DESCRIPTION
**Pull request by njhale**
This reverts commit 3a4c2b201c145d2b63092687921a8ad0ec79c5ae, reversing
changes made to 69b27962caf2b7eeb7e2a157597fbf9e5e3b46fe.

/hold

### CODE REVIEW

**Comment by njhale** [comment]
#791 Fixes the issue this revert is resolving

**Comment by ecordell** [comment]
Fixed in #791

**Pull request closed without merging**
